import { Express } from "express";
import healthRoutes from "./health.routes";
import authRoutes from "./auth.routes";
import chatRoutes from "./chat.routes";
import conversationsRoutes from "./conversations.routes";
import roomsRoutes from "./rooms.routes";
import groupsRoutes from "./groups.routes";
import pollsRoutes from "./polls.routes";
import projectsRoutes from "./projects.routes";
import usersRoutes from "./users.routes";
import settingsRoutes from "./settings.routes";
import searchRoutes from "./search.routes";
import moderationRoutes from "./moderation.routes";
import adminRoutes from "./admin.routes";
import analyticsRoutes from "./analytics.routes";
import exportRoutes from "./export.routes";
import memoryRoutes from "./memory.routes";
import uploadsRoutes from "./uploads.routes";
import aiRoutes from "./ai.routes";
import importRoutes from "./import.routes";

export const registerRoutes = (app: Express): void => {
    app.use("/api/health", healthRoutes);
    app.use("/api/auth", authRoutes);
    app.use("/api/chat", chatRoutes);
    app.use("/api/conversations", conversationsRoutes);
    app.use("/api/rooms", roomsRoutes);
    app.use("/api/groups", groupsRoutes);
    app.use("/api/polls", pollsRoutes);
    app.use("/api/projects", projectsRoutes);
    app.use("/api/users", usersRoutes);
    app.use("/api/settings", settingsRoutes);
    app.use("/api/search", searchRoutes);
    app.use("/api/moderation", moderationRoutes);
    app.use("/api/admin", adminRoutes);
    app.use("/api/analytics", analyticsRoutes);
    app.use("/api/export", exportRoutes);
    app.use("/api/memory", memoryRoutes);
    app.use("/api/uploads", uploadsRoutes);
    app.use("/api/ai", aiRoutes);
    app.use("/api/import", importRoutes);
};
